# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
      CONDA_DEPENDENCIES: "requests beautifulsoup4 matplotlib html5lib keyring=11 aplpy sip=4.18 regions"
      PIP_DEPENDENCIES: "pyregion astropy_healpix mocpy>=0.5.2 pytest-astropy"
      CONDA_CHANNELS: "astropy"
      ASTROPY_USE_SYSTEM_PYTEST: 1

  matrix:
      - PYTHON_VERSION: "2.7"
        ASTROPY_VERSION: "LTS"
        NUMPY_VERSION: "1.13"

      - PYTHON_VERSION: "3.6"
        ASTROPY_VERSION: "stable"
        NUMPY_VERSION: "stable"

platform:
    -x64

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

# Not a .NET project, we build the package in the install step instead
build: false

test_script:
    - "%CMD_IN_ENV% python setup.py test"
